
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_CauseEffectCurProblemInfo
{

    public int ID { get; set; }

    public int ProjectID { get; set; }

    public string ProblemDescription { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public string AltinativeProblem { get; set; }

    public string TechConflict { get; set; }

    public string PhyConflict { get; set; }

}

}
