
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_QuestionAnalyseInfo
{

    public int ID { get; set; }

    public Nullable<int> ProjectID { get; set; }

    public string IdealResolution1 { get; set; }

    public string IdealResolution2 { get; set; }

    public string IdealResolution3 { get; set; }

    public string IdealResolution4 { get; set; }

    public string IdealResolution5 { get; set; }

    public string BasicQuestion1 { get; set; }

    public string BasicQuestion2 { get; set; }

    public string BasicQuestion3 { get; set; }

    public string BasicQuestion4 { get; set; }

    public string AgainstObject1 { get; set; }

    public string AgainstObject2 { get; set; }

    public string AgainstObject3 { get; set; }

    public string AgainstObject4 { get; set; }

    public string AgainstObject5 { get; set; }

    public string Constriction1 { get; set; }

    public string Constriction2 { get; set; }

    public string Constriction3 { get; set; }

    public string Constriction4 { get; set; }

    public string Constriction5 { get; set; }

    public string ResolutionImportance1 { get; set; }

    public string ResolutionImportance2 { get; set; }

    public string ResolutionImportance3 { get; set; }

    public string ResolutionImportance4 { get; set; }

    public string ResolutionImportance5 { get; set; }

    public System.DateTime CreateDateTime { get; set; }

}

}
