
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_TechnicalConflictResolveInfo
{

    public int ID { get; set; }

    public int ProjectID { get; set; }

    public Nullable<int> SerialNum { get; set; }

    public int TechnicalConflictID { get; set; }

    public string ForwardCharacter { get; set; }

    public string BackwardCharacter { get; set; }

    public string InventivePrincipleID { get; set; }

    public string InventivePrincipleName { get; set; }

    public string CaseID { get; set; }

    public string CaseName { get; set; }

    public string Remark { get; set; }

    public System.DateTime CreateDateTime { get; set; }

}

}
