
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_FunEleMutualReactInfo
{

    public int ID { get; set; }

    public Nullable<int> ProjectID { get; set; }

    public Nullable<int> PositiveEleID { get; set; }

    public string PositiveEleName { get; set; }

    public string PositiveEleType { get; set; }

    public string FunctionName { get; set; }

    public Nullable<int> PassiveEleID { get; set; }

    public string PassiveEleName { get; set; }

    public string PassiveEleType { get; set; }

    public string FunctionType { get; set; }

    public string FunctionGrade { get; set; }

    public string ElementType { get; set; }

    public System.DateTime CreateDateTime { get; set; }

}

}
