
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ConflictInfo
{

    public int ID { get; set; }

    public int ProjectID { get; set; }

    public string RelComponentName { get; set; }

    public string RelComponentParamName { get; set; }

    public string CurrentConfig { get; set; }

    public string ChangeConfig { get; set; }

    public string CurrentProblem { get; set; }

    public string NewProblem { get; set; }

    public System.DateTime CreateDateTime { get; set; }

}

}
