

//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Triz.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TrizDBEntities : DbContext
{
    public TrizDBEntities()
        : base("name=TrizDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<tbl_ProjectInfo> tbl_ProjectInfo { get; set; }

    public DbSet<tbl_UserProjectInfo> tbl_UserProjectInfo { get; set; }

    public DbSet<tbl_QuestionDescriptionInfo> tbl_QuestionDescriptionInfo { get; set; }

    public DbSet<tbl_UserInfo> tbl_UserInfo { get; set; }

    public DbSet<tbl_QuestionAnalyseInfo> tbl_QuestionAnalyseInfo { get; set; }

    public DbSet<tbl_FunctionElementInfo> tbl_FunctionElementInfo { get; set; }

    public DbSet<tbl_FunEleMutualReactInfo> tbl_FunEleMutualReactInfo { get; set; }

    public DbSet<tbl_CauseEffectCurProblemInfo> tbl_CauseEffectCurProblemInfo { get; set; }

    public DbSet<tbl_ComponentParamInfo> tbl_ComponentParamInfo { get; set; }

    public DbSet<tbl_ComponentRelInfo> tbl_ComponentRelInfo { get; set; }

    public DbSet<tbl_StandardSolutionExampleInfo> tbl_StandardSolutionExampleInfo { get; set; }

    public DbSet<tbl_ConflictInfo> tbl_ConflictInfo { get; set; }

    public DbSet<tbl_StandardSolutionInfo> tbl_StandardSolutionInfo { get; set; }

    public DbSet<tbl_MaterialFieldModelInfo> tbl_MaterialFieldModelInfo { get; set; }

    public DbSet<tbl_AnalysisProcedureInfo> tbl_AnalysisProcedureInfo { get; set; }

    public DbSet<tbl_TechnicalConflictInfo> tbl_TechnicalConflictInfo { get; set; }

    public DbSet<tbl_PhysicalConflictInfo> tbl_PhysicalConflictInfo { get; set; }

    public DbSet<tbl_TechnicalConflictResolveInfo> tbl_TechnicalConflictResolveInfo { get; set; }

    public DbSet<tbl_DictionaryTreeInfo> tbl_DictionaryTreeInfo { get; set; }

}

}

